"""Base class for all VC blog sources.

Design note — why link harvesting instead of CSS selectors
----------------------------------------------------------
The obvious way to parse a blog index is to find the post-card container and
walk its children. That's what vc-job-agent's scrapers did, and
SCRAPER_DIAGNOSIS.md is the record of all 13 of them breaking at once.

These are marketing sites. Their class names are build-hashed
(`_card_a8f3d2`), their DOM nesting is regenerated by Webflow/Next.js on every
deploy, and none of it is a stable contract. What *is* stable is the URL shape
of a post: Greylock posts live at `/blog/<slug>/`, a16z investment
announcements at `/announcement/<slug>/`, General Catalyst stories at
`/stories/<slug>`. Those paths are public, linkable, and rarely change — they'd
break inbound links and SEO.

So the default strategy is: harvest every anchor on the index page, keep the
hrefs matching a per-site `post_url_pattern`, and reject the ones matching
`exclude_url_patterns` (category pages, pagination, the index itself). Titles
come from the anchor text, and each subclass can refine them.

This trades a little precision for a lot of durability. A source that has a
real feed should subclass `RSSSource` instead — feeds are a contract.
"""

from __future__ import annotations

import logging
import re
import time
from abc import ABC, abstractmethod
from datetime import datetime, timedelta
from typing import Iterable, Optional
from urllib.parse import urljoin, urlparse, urlunparse

import requests
from bs4 import BeautifulSoup

from ..models import BlogPost

logger = logging.getLogger(__name__)

# Query params that are pure tracking noise — stripped during canonicalization
# so the same post arriving via a newsletter link dedups against the plain URL.
TRACKING_PARAMS = {
    "utm_source", "utm_medium", "utm_campaign", "utm_term", "utm_content",
    "utm_id", "gclid", "fbclid", "mc_cid", "mc_eid", "ref", "referrer",
    "source", "hsCtaTracking", "_hsenc", "_hsmi",
}

# Non-post links that show up on every blog index
GENERIC_EXCLUDES = [
    r"/(page|p)/\d+/?$",
    r"/(tag|tags|category|categories|topic|topics|author|authors)/",
    r"\.(pdf|jpg|jpeg|png|svg|webp|gif|mp4|zip)$",
    r"^mailto:",
    r"^tel:",
    r"#",
]


def canonicalize_url(url: str, base: str = "") -> str:
    """Normalize a URL so it can serve as a stable dedup key.

    Resolves relative links, lowercases the host, drops tracking params and
    fragments, and normalizes the trailing slash away.
    """
    if not url:
        return ""
    url = url.strip()
    if base:
        url = urljoin(base, url)

    parsed = urlparse(url)
    if parsed.scheme not in ("http", "https"):
        return ""

    # Keep meaningful query params, drop tracking ones
    query = ""
    if parsed.query:
        kept = []
        for part in parsed.query.split("&"):
            if not part:
                continue
            key = part.split("=", 1)[0]
            if key not in TRACKING_PARAMS:
                kept.append(part)
        query = "&".join(sorted(kept))

    path = parsed.path.rstrip("/") or "/"

    return urlunparse((
        parsed.scheme,
        parsed.netloc.lower(),
        path,
        "",
        query,
        "",  # drop fragment
    ))


def registrable_host(url: str) -> str:
    """Host of a URL with a leading `www.` removed.

    `www.example.com` and `example.com` are the same site by universal
    convention, and feeds routinely disagree with the page they describe about
    which form to emit: Sequoia's index is served from www.sequoiacap.com while
    every entry in its RSS feed points at sequoiacap.com. A literal netloc
    comparison rejects all of them.

    Only the `www.` label is stripped. Any other subdomain is a genuinely
    different host and must stay one — jobs.greylock.com is not greylock.com,
    which is exactly the kind of cross-property link this check exists to drop.
    """
    host = urlparse(url).netloc.lower()
    return host[4:] if host.startswith("www.") else host


def same_site(url: str, other: str) -> bool:
    """Are these two URLs on the same site, ignoring a `www.` prefix?"""
    return registrable_host(url) == registrable_host(other)


class BaseSource(ABC):
    """Base class for a single VC firm's blog."""

    name: str = "Base"
    base_url: str = ""
    index_urls: list[str] = []

    # Regex an href must match to count as a post
    post_url_pattern: str = r".*"
    # Regexes that disqualify an href even if it matched above
    exclude_url_patterns: list[str] = []

    # If a post URL matches this, it's an investment announcement and the
    # classifier can be skipped. a16z's /announcement/ path is the clean case.
    investment_url_pattern: Optional[str] = None
    # Title prefixes that reliably indicate an announcement, e.g. "Investing in".
    investment_title_patterns: list[str] = []
    # Category/tag values that reliably indicate one. Feeds and card labels
    # often carry the firm's own classification, which beats any title
    # heuristic — Sequoia tags funding posts "Funding announcement".
    investment_label_patterns: list[str] = []

    # Politeness delay between requests to the same host
    request_delay: float = 1.0
    # How many index pages deep to walk before stopping
    max_pages: int = 3

    def __init__(self, session: Optional[requests.Session] = None):
        self.session = session or requests.Session()
        self.session.headers.update({
            "User-Agent": (
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            ),
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.9",
        })

    # ------------------------------------------------------------------
    # Fetching
    # ------------------------------------------------------------------

    def fetch_page(self, url: str, delay: Optional[float] = None) -> Optional[BeautifulSoup]:
        """Fetch a URL and return parsed HTML, or None on failure."""
        try:
            time.sleep(self.request_delay if delay is None else delay)
            resp = self.session.get(url, timeout=30)
            resp.raise_for_status()
            return BeautifulSoup(resp.text, "lxml")
        except requests.RequestException as e:
            logger.error(f"[{self.name}] Failed to fetch {url}: {e}")
            return None

    def fetch_json(self, url: str, delay: Optional[float] = None, **kwargs) -> Optional[dict]:
        """Fetch JSON from a URL, or None on failure."""
        try:
            time.sleep(self.request_delay if delay is None else delay)
            resp = self.session.get(url, timeout=30, **kwargs)
            resp.raise_for_status()
            return resp.json()
        except (requests.RequestException, ValueError) as e:
            logger.error(f"[{self.name}] Failed to fetch JSON from {url}: {e}")
            return None

    # ------------------------------------------------------------------
    # Discovery — the default link-harvest strategy
    # ------------------------------------------------------------------

    def scrape(self) -> list[BlogPost]:
        """Discover posts across all index pages. Override for custom sources."""
        seen: set[str] = set()
        posts: list[BlogPost] = []

        for index_url in self.index_urls or [self.base_url]:
            for page_url in self.paginate(index_url):
                soup = self.fetch_page(page_url)
                if soup is None:
                    break

                page_posts = self.parse_index(soup, page_url)
                fresh = [p for p in page_posts if p.url not in seen]
                for p in fresh:
                    seen.add(p.url)
                posts.extend(fresh)

                # Stop paginating once a page yields nothing new — either we've
                # hit the end or the pagination scheme isn't working.
                if not fresh:
                    logger.debug(f"[{self.name}] No new posts on {page_url}, stopping pagination")
                    break

        logger.info(f"[{self.name}] Discovered {len(posts)} posts")
        return posts

    def paginate(self, index_url: str) -> Iterable[str]:
        """Yield index page URLs. Default: just the first page.

        Override with e.g. `f"{index_url}page/{n}/"` where pagination exists.
        """
        yield index_url

    def parse_index(self, soup: BeautifulSoup, page_url: str) -> list[BlogPost]:
        """Harvest post links from an index page."""
        posts: list[BlogPost] = []
        seen: set[str] = set()

        for anchor in soup.find_all("a", href=True):
            url = canonicalize_url(anchor["href"], base=page_url)
            if not url or url in seen:
                continue
            if not self.is_post_url(url):
                continue

            title = self.extract_title(anchor)
            if not title:
                continue

            labels = self.extract_labels(anchor)
            seen.add(url)
            posts.append(BlogPost(
                url=url,
                title=title,
                vc_firm=self.name,
                published_date=self.extract_date_near(anchor),
                labels=labels,
                likely_investment=self.looks_like_investment(url, title, labels),
            ))

        return posts

    def is_post_url(self, url: str) -> bool:
        """Does this URL look like an individual post on this blog?"""
        # Must be on the same host — external coverage links are not our posts
        if self.base_url:
            if not same_site(url, self.base_url):
                return False

        for pattern in GENERIC_EXCLUDES + self.exclude_url_patterns:
            if re.search(pattern, url, re.IGNORECASE):
                return False

        return bool(re.search(self.post_url_pattern, url, re.IGNORECASE))

    def looks_like_investment(
        self, url: str, title: str, labels: Optional[list[str]] = None
    ) -> Optional[bool]:
        """Cheap pre-classification from URL, title, or the firm's own tags.

        Returns True when confident, None when unknown. Never returns False —
        a negative here would silently drop posts, and that decision belongs to
        the LLM classifier which can actually read the post.
        """
        if self.investment_url_pattern and re.search(
            self.investment_url_pattern, url, re.IGNORECASE
        ):
            return True
        for pattern in self.investment_title_patterns:
            if re.search(pattern, title, re.IGNORECASE):
                return True
        for pattern in self.investment_label_patterns:
            for label in labels or []:
                if re.search(pattern, label, re.IGNORECASE):
                    return True
        return None

    def extract_title(self, anchor) -> str:
        """Pull a usable title out of an anchor element."""
        # Prefer a heading inside the anchor — index cards usually nest one
        heading = anchor.find(["h1", "h2", "h3", "h4", "h5", "h6"])
        if heading:
            text = self.clean_text(heading.get_text(" ", strip=True))
            if len(text) > 3:
                return text

        text = self.clean_text(anchor.get_text(" ", strip=True))
        if len(text) > 3:
            return text

        # Fall back to accessible names, then to the slug
        for attr in ("aria-label", "title"):
            val = self.clean_text(anchor.get(attr, ""))
            if len(val) > 3:
                return val

        slug = urlparse(anchor.get("href", "")).path.rstrip("/").split("/")[-1]
        return slug.replace("-", " ").title() if slug else ""

    def extract_labels(self, anchor) -> list[str]:
        """Category/topic labels near a post link. Override per source."""
        return []

    def extract_date_near(self, anchor) -> Optional[datetime]:
        """Look for a <time> element in or near the anchor."""
        for scope in (anchor, anchor.parent, getattr(anchor.parent, "parent", None)):
            if scope is None:
                continue
            time_el = scope.find("time") if hasattr(scope, "find") else None
            if time_el:
                for attr in ("datetime", "data-date"):
                    if time_el.get(attr):
                        parsed = self.parse_date(time_el[attr])
                        if parsed:
                            return parsed
                parsed = self.parse_date(time_el.get_text(strip=True))
                if parsed:
                    return parsed
        return None

    # ------------------------------------------------------------------
    # Detail page — ported from vc-job-agent BaseScraper.fetch_job_detail()
    # ------------------------------------------------------------------

    DETAIL_SELECTORS = [
        "article",
        "[class*='post-body']",
        "[class*='postBody']",
        "[class*='post-content']",
        "[class*='article-body']",
        "[class*='rich-text']",
        "[class*='RichText']",
        "[class*='prose']",
        "main",
        "[role='main']",
    ]

    STRIP_TAGS = [
        "script", "style", "nav", "header", "footer", "noscript",
        "form", "aside", "iframe", "svg",
    ]

    def fetch_post_detail(self, post: BlogPost) -> BlogPost:
        """Follow a post URL and fill in its body text.

        This is the "access an additional page and scrape the content on said
        page" step. Mutates and returns the post; failures leave it unchanged
        so one bad page can't sink the run.
        """
        try:
            soup = self.fetch_page(post.url, delay=0.4)
            if soup is None:
                return post

            for tag in soup.find_all(self.STRIP_TAGS):
                tag.decompose()

            container = None
            for selector in self.DETAIL_SELECTORS:
                el = soup.select_one(selector)
                if el and len(el.get_text(strip=True)) > 300:
                    container = el
                    break
            if container is None:
                container = soup.find("body")
            if container is None:
                return post

            post.body = self.clean_text(container.get_text("\n", strip=True))[:12000]

            # A date on the detail page is more trustworthy than one guessed
            # from the index card
            if post.published_date is None:
                post.published_date = self.extract_detail_date(soup)

            # Prefer the detail page's own <title>/<h1> over harvested anchor text
            if len(post.title) < 5:
                h1 = soup.find("h1")
                if h1:
                    post.title = self.clean_text(h1.get_text(" ", strip=True))

        except Exception as e:  # noqa: BLE001 — one bad page must not kill the run
            logger.debug(f"[{self.name}] Detail fetch failed for {post.url}: {e}")

        return post

    def extract_detail_date(self, soup: BeautifulSoup) -> Optional[datetime]:
        """Find a publication date on a post's own page.

        Meta tags first — they're machine-readable and usually accurate.
        """
        meta_names = [
            ("property", "article:published_time"),
            ("name", "article:published_time"),
            ("property", "og:published_time"),
            ("name", "publish-date"),
            ("name", "date"),
            ("itemprop", "datePublished"),
        ]
        for attr, value in meta_names:
            tag = soup.find("meta", attrs={attr: value})
            if tag and tag.get("content"):
                parsed = self.parse_date(tag["content"])
                if parsed:
                    return parsed

        time_el = soup.find("time")
        if time_el:
            candidate = time_el.get("datetime") or time_el.get_text(strip=True)
            parsed = self.parse_date(candidate)
            if parsed:
                return parsed

        return None

    # ------------------------------------------------------------------
    # Utilities
    # ------------------------------------------------------------------

    DATE_FORMATS = [
        "%Y-%m-%dT%H:%M:%S.%fZ",
        "%Y-%m-%dT%H:%M:%S%z",
        "%Y-%m-%dT%H:%M:%SZ",
        "%Y-%m-%dT%H:%M:%S",
        "%Y-%m-%d",
        "%m/%d/%Y",
        "%B %d, %Y",
        "%b %d, %Y",
        "%d %B %Y",
    ]

    @classmethod
    def parse_date(cls, value: Optional[str]) -> Optional[datetime]:
        """Parse a date string across the formats these sites actually use."""
        if not value or not isinstance(value, str):
            return None
        text = value.strip()
        if not text:
            return None

        for fmt in cls.DATE_FORMATS:
            try:
                dt = datetime.strptime(text, fmt)
                return dt.replace(tzinfo=None)
            except ValueError:
                continue

        # Relative dates ("3 days ago") appear on a few of these sites
        rel = re.match(
            r"(\d+)\s+(minute|hour|day|week|month|year)s?\s+ago", text, re.IGNORECASE
        )
        if rel:
            n = int(rel.group(1))
            unit = rel.group(2).lower()
            deltas = {
                "minute": timedelta(minutes=n),
                "hour": timedelta(hours=n),
                "day": timedelta(days=n),
                "week": timedelta(weeks=n),
                "month": timedelta(days=30 * n),
                "year": timedelta(days=365 * n),
            }
            return datetime.utcnow() - deltas[unit]

        try:
            from dateutil import parser as dateutil_parser

            return dateutil_parser.parse(text, fuzzy=False).replace(tzinfo=None)
        except Exception:  # noqa: BLE001
            return None

    @staticmethod
    def clean_text(text: str) -> str:
        """Collapse whitespace while preserving paragraph breaks."""
        if not text:
            return ""
        text = text.replace(" ", " ")
        text = re.sub(r"[ \t]+", " ", text)
        text = re.sub(r"\n{3,}", "\n\n", text)
        return text.strip()
